version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: nge-eat-laravel
    container_name: nge-eat-app
    restart: always
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - 9000:9000
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: nge-eat-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: nge_eat123
      MYSQL_DATABASE: nge_eat
    ports:
      - 3307:3306
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: nge-eat-pma
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: nge_eat123
    ports:
      - 8081:80
    depends_on:
      - db

volumes:
  dbdata:
